### ISSUE TITLE
TypeError: string argument expected, got 'bytes'

### ISSUE THREAD

**Issue by RJ109** [lintool/Enron2mbox#1]
Hi, 
The code runs and begins processing the maildir, however as soon as it starts writing i get the error below: 

Traceback (most recent call last):
  File "/Users/rj101/Desktop/enron2mbox.py", line 46, in <module>
    maildir2mailbox(str(folder), str(path))
  File "/Users/rj101/Desktop/enron2mbox.py", line 19, in maildir2mailbox
    for msg in maildir:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/mailbox.py", line 109, in itervalues
    value = self[key]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/mailbox.py", line 76, in __getitem__
    return self._factory(file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/email/__init__.py", line 54, in message_from_file
    return Parser(*args, **kws).parse(fp)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/email/parser.py", line 57, in parse
    feedparser.feed(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/email/feedparser.py", line 175, in feed
    self._input.push(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/email/feedparser.py", line 103, in push
    self._partial.write(data)
TypeError: string argument expected, got 'bytes'

Process finished with exit code 1

Thanks for any help in advance

**Comment by ylwang99** [comment]
Hi,

I didn't see enron2mbox.py in this repo. Are you trying to run convert_enron_to_mbox.py?

If so, please make sure that convert_enron_to_mbox.py is in the same folder as maildir/ direcotry (by moving maildir/ to Enron2mbox/), that is extracted from enron_mail_20150507.tar.gz.

**Comment by RJ109** [comment]
Hi,
I simply changed the name of the file. enron2mbox.py = convert_enron_to_mbox.py,
I have followed the readme instructions and have run within the same folder, however i still get the error

**Comment by ylwang99** [comment]
You can run with Python 2.7.
For Python newer than 2.7, you can simply change line [12](https://github.com/lintool/Enron2mbox/blob/master/convert_enron_to_mbox.py#L12) `maildir = mailbox.Maildir(maildirname, email.message_from_file)` to `maildir = mailbox.Maildir(maildirname)`.
